services:
  accounts-db:
    image: postgres:16
    container_name: cloudbank-accounts-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cloudbank
      POSTGRES_PASSWORD: cloudbank_dev_pw
      POSTGRES_DB: accounts_db
    ports:
      - "5432:5432"
    volumes:
      - accounts_db_data:/var/lib/postgresql/data

  transactions-db:
    image: postgres:16
    container_name: cloudbank-transactions-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cloudbank
      POSTGRES_PASSWORD: cloudbank_dev_pw
      POSTGRES_DB: transactions_db
    ports:
      - "5433:5432"
    volumes:
      - transactions_db_data:/var/lib/postgresql/data

volumes:
  accounts_db_data:
  transactions_db_data: